# Generated by Django 3.2.4 on 2021-07-04 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'заметку',
                'verbose_name_plural': 'Заметки',
            },
        ),
        migrations.CreateModel(
            name='eng_ru_word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=30)),
                ('russian_word', models.CharField(max_length=30)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.note')),
            ],
            options={
                'verbose_name': 'слова',
                'verbose_name_plural': 'Словарь',
            },
        ),
    ]
