# Generated by Django 3.2.4 on 2021-07-05 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_eng_ru_word_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eng_ru_word',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_key', to='main.note'),
        ),
    ]
